window.VOCAB_DATA = [
  {
    className: "Class 8 下",
    units: [
      { unitName: "Unit 1", words: [
        { id: "class8b-unit1-self-expression", word: "self-expression", meaning: "自我表达" },
        { id: "class8b-unit1-creativity", word: "creativity", meaning: "创造力" },
        { id: "class8b-unit1-require", word: "require", meaning: "需要；依靠" },
        { id: "class8b-unit1-scissors", word: "scissors", meaning: "剪刀" },
        { id: "class8b-unit1-drama", word: "drama", meaning: "戏剧" },
        { id: "class8b-unit1-acting", word: "acting", meaning: "表演" },
        { id: "class8b-unit1-normal", word: "normal", meaning: "典型的；正常的" },
        { id: "class8b-unit1-prefer-to", word: "prefer ... to", meaning: "更喜欢……" },
        { id: "class8b-unit1-pottery", word: "pottery", meaning: "陶器；制陶技艺" },
        { id: "class8b-unit1-rather-than", word: "rather than", meaning: "而不是" },
        { id: "class8b-unit1-position", word: "position", meaning: "位置；地方" },
        { id: "class8b-unit1-instrument", word: "instrument", meaning: "器具；仪器" },
        { id: "class8b-unit1-sculpture", word: "sculpture", meaning: "雕塑；雕塑作品" },
        { id: "class8b-unit1-sculptor", word: "sculptor", meaning: "雕塑家；雕刻家" },
        { id: "class8b-unit1-landscape", word: "landscape", meaning: "风景；景色" },
        { id: "class8b-unit1-master", word: "master", meaning: "能手；大师；擅长……的人" },
        { id: "class8b-unit1-dynasty", word: "dynasty", meaning: "王朝；朝代" },
        { id: "class8b-unit1-paint", word: "paint", meaning: "绘画" },
        { id: "class8b-unit1-harmony", word: "harmony", meaning: "融洽；和谐" },
        { id: "class8b-unit1-path", word: "path", meaning: "小道；小径" },
        { id: "class8b-unit1-ahead", word: "ahead", meaning: "在前方" },
        { id: "class8b-unit1-whoever", word: "whoever", meaning: "无论谁；不管什么人" },
        { id: "class8b-unit1-come-across", word: "come across", meaning: "偶然遇见；碰见；发现" },
        { id: "class8b-unit1-scare", word: "scare", meaning: "惊吓；使害怕；使恐惧" },
        { id: "class8b-unit1-scared", word: "scared", meaning: "害怕的；恐惧的；担心的" },
        { id: "class8b-unit1-vivid", word: "vivid", meaning: "生动的；逼真的" },
        { id: "class8b-unit1-east", word: "east", meaning: "东；东方；东部" },
        { id: "class8b-unit1-west", word: "west", meaning: "西；西方；西部" },
        { id: "class8b-unit1-peaceful", word: "peaceful", meaning: "安静的；宁静的" }
      ]},
      { unitName: "Unit 2", words: [
        { id: "class8b-unit2-discovery", word: "discovery", meaning: "发现；发觉" },
        { id: "class8b-unit2-ancient", word: "ancient", meaning: "古代的；古老的" },
        { id: "class8b-unit2-bce", word: "BCE", meaning: "公元前" },
        { id: "class8b-unit2-exploration", word: "exploration", meaning: "探索；勘查" },
        { id: "class8b-unit2-wheel", word: "wheel", meaning: "轮子；车轮" },
        { id: "class8b-unit2-ce", word: "CE", meaning: "公元" },
        { id: "class8b-unit2-economy", word: "economy", meaning: "经济" },
        { id: "class8b-unit2-material", word: "material", meaning: "材料；原料" },
        { id: "class8b-unit2-fishnet", word: "fishnet", meaning: "渔网" },
        { id: "class8b-unit2-war", word: "war", meaning: "战争" },
        { id: "class8b-unit2-illness", word: "illness", meaning: "疾病；病" },
        { id: "class8b-unit2-socialism", word: "socialism", meaning: "社会主义" },
        { id: "class8b-unit2-habit", word: "habit", meaning: "习惯" },
        { id: "class8b-unit2-totally", word: "totally", meaning: "全部地；整个地" },
        { id: "class8b-unit2-tube", word: "tube", meaning: "管；管子" },
        { id: "class8b-unit2-bone", word: "bone", meaning: "骨头" },
        { id: "class8b-unit2-x-ray", word: "X-ray", meaning: "X 射线；X 光" },
        { id: "class8b-unit2-award", word: "award", meaning: "颁奖；奖；奖品" },
        { id: "class8b-unit2-sir", word: "sir", meaning: "爵士；先生" },
        { id: "class8b-unit2-by-accident", word: "by accident", meaning: "偶然；意外地" },
        { id: "class8b-unit2-to-ones-surprise", word: "to one's surprise", meaning: "令某人惊讶的是" },
        { id: "class8b-unit2-turn-into", word: "turn ... into", meaning: "使……变成" },
        { id: "class8b-unit2-life-saving", word: "life-saving", meaning: "救命的；救生的" },
        { id: "class8b-unit2-course", word: "course", meaning: "进程；课程" },
        { id: "class8b-unit2-treat", word: "treat", meaning: "医治；治疗" },
        { id: "class8b-unit2-serious", word: "serious", meaning: "严重的；严肃的" },
        { id: "class8b-unit2-medical", word: "medical", meaning: "医学的；医疗的" },
        { id: "class8b-unit2-light-up", word: "light up", meaning: "使……变亮" },
        { id: "class8b-unit2-volunteer", word: "volunteer", meaning: "自愿做；义务做；无偿做" },
        { id: "class8b-unit2-herself", word: "herself", meaning: "她自己；自己" },
        { id: "class8b-unit2-keep-in-touch", word: "keep in touch", meaning: "保持联系" },
        { id: "class8b-unit2-spare", word: "spare", meaning: "空闲的" }
      ]},
      { unitName: "Unit 3", words: [
        { id: "class8b-unit3-mall", word: "mall", meaning: "购物商场；购物广场" },
        { id: "class8b-unit3-sale", word: "sale", meaning: "出售；特价销售" },
        { id: "class8b-unit3-payment", word: "payment", meaning: "支付；付款；收款" },
        { id: "class8b-unit3-cash", word: "cash", meaning: "现金" },
        { id: "class8b-unit3-honey", word: "honey", meaning: "亲爱的；宝贝" },
        { id: "class8b-unit3-assistant", word: "assistant", meaning: "店员；助手" },
        { id: "class8b-unit3-deal", word: "deal", meaning: "交易；协议" },
        { id: "class8b-unit3-bill", word: "bill", meaning: "账单" },
        { id: "class8b-unit3-donate", word: "donate", meaning: "捐赠；赠送" },
        { id: "class8b-unit3-pound", word: "pound", meaning: "英镑；磅" },
        { id: "class8b-unit3-cheap", word: "cheap", meaning: "便宜的；廉价的" },
        { id: "class8b-unit3-chocolate", word: "chocolate", meaning: "巧克力" },
        { id: "class8b-unit3-pocket", word: "pocket", meaning: "衣袋；口袋" },
        { id: "class8b-unit3-pocket-money", word: "pocket money", meaning: "零花钱" },
        { id: "class8b-unit3-expectation", word: "expectation", meaning: "期望；预期" },
        { id: "class8b-unit3-budget", word: "budget", meaning: "做预算；预算" },
        { id: "class8b-unit3-in-short", word: "in short", meaning: "总之；简而言之" },
        { id: "class8b-unit3-independent", word: "independent", meaning: "独立的；自主的" },
        { id: "class8b-unit3-responsible", word: "responsible", meaning: "负责的；负责任的；可信任的" },
        { id: "class8b-unit3-mess", word: "mess", meaning: "使不整洁；弄脏；弄乱" },
        { id: "class8b-unit3-mess-up", word: "mess up", meaning: "出错；搞砸；处理不当" },
        { id: "class8b-unit3-responsibility", word: "responsibility", meaning: "责任；负责" },
        { id: "class8b-unit3-value", word: "value", meaning: "用途；积极作用；价值" },
        { id: "class8b-unit3-account", word: "account", meaning: "账户" },
        { id: "class8b-unit3-bank", word: "bank", meaning: "银行" },
        { id: "class8b-unit3-economics", word: "economics", meaning: "经济学" },
        { id: "class8b-unit3-whatever", word: "whatever", meaning: "任何事物；什么都可以" },
        { id: "class8b-unit3-economist", word: "economist", meaning: "经济学家；经济专家" },
        { id: "class8b-unit3-society", word: "society", meaning: "社会" },
        { id: "class8b-unit3-trade", word: "trade", meaning: "互相交换；贸易；交易" },
        { id: "class8b-unit3-goods", word: "goods", meaning: "商品；货品" },
        { id: "class8b-unit3-exchange", word: "exchange", meaning: "交换；互换" },
        { id: "class8b-unit3-sample", word: "sample", meaning: "样品；试用产品" },
        { id: "class8b-unit3-saying", word: "saying", meaning: "谚语；格言；警句" },
        { id: "class8b-unit3-cost", word: "cost", meaning: "成本；花费；价钱为" },
        { id: "class8b-unit3-even-if", word: "even if", meaning: "即使；纵然；虽然" },
        { id: "class8b-unit3-might", word: "might", meaning: "可能；可以" },
        { id: "class8b-unit3-complete", word: "complete", meaning: "完全的；彻底的；完成；使完整" },
        { id: "class8b-unit3-completely", word: "completely", meaning: "完全地；彻底地" },
        { id: "class8b-unit3-valuable", word: "valuable", meaning: "很有用的；很重要的；宝贵的" },
        { id: "class8b-unit3-pie", word: "pie", meaning: "果馅饼；果馅派" },
        { id: "class8b-unit3-pie-chart", word: "pie chart", meaning: "饼状图" },
        { id: "class8b-unit3-percentage", word: "percentage", meaning: "百分率；百分比" },
        { id: "class8b-unit3-account-for", word: "account for", meaning: "占（数量上、比例上）" }
      ]},
      { unitName: "Unit 4", words: [
        { id: "class8b-unit4-fashion", word: "fashion", meaning: "时尚" },
        { id: "class8b-unit4-trainers", word: "trainers", meaning: "运动鞋；便鞋" },
        { id: "class8b-unit4-decoration", word: "decoration", meaning: "装饰；装饰品" },
        { id: "class8b-unit4-afford", word: "afford", meaning: "买得起；承担得起" },
        { id: "class8b-unit4-changeable", word: "changeable", meaning: "易变的；常变的" },
        { id: "class8b-unit4-energetic", word: "energetic", meaning: "精力充沛的；充满活力的" },
        { id: "class8b-unit4-fashionable", word: "fashionable", meaning: "流行的；时髦的" },
        { id: "class8b-unit4-flowery", word: "flowery", meaning: "用花装饰的" },
        { id: "class8b-unit4-outfit", word: "outfit", meaning: "全套服装；装束" },
        { id: "class8b-unit4-narrow", word: "narrow", meaning: "狭窄的；窄小的" },
        { id: "class8b-unit4-baggy", word: "baggy", meaning: "宽松的" },
        { id: "class8b-unit4-advertising", word: "advertising", meaning: "广告活动；广告业；广告" },
        { id: "class8b-unit4-a-great-deal-of", word: "a great deal of", meaning: "很多；大量" },
        { id: "class8b-unit4-advertisement", word: "advertisement", meaning: "广告；启事" },
        { id: "class8b-unit4-image", word: "image", meaning: "形象；印象；图像" },
        { id: "class8b-unit4-pioneer", word: "pioneer", meaning: "先锋；先驱；带头人" },
        { id: "class8b-unit4-influencer", word: "influencer", meaning: "有影响力的人" },
        { id: "class8b-unit4-jewellery", word: "jewellery", meaning: "珠宝；首饰" },
        { id: "class8b-unit4-attract", word: "attract", meaning: "吸引；引起……的好感" },
        { id: "class8b-unit4-fit", word: "fit", meaning: "使适合；合身" },
        { id: "class8b-unit4-relaxed", word: "relaxed", meaning: "放松的；自在的" },
        { id: "class8b-unit4-mention", word: "mention", meaning: "提到；写到；谈到" },
        { id: "class8b-unit4-grade", word: "grade", meaning: "分数" },
        { id: "class8b-unit4-interest", word: "interest", meaning: "兴趣；爱好" }
      ]},
      { unitName: "Unit 5", words: [
        { id: "class8b-unit5-disaster", word: "disaster", meaning: "灾难；灾害" },
        { id: "class8b-unit5-flood", word: "flood", meaning: "洪水；水灾" },
        { id: "class8b-unit5-earthquake", word: "earthquake", meaning: "地震" },
        { id: "class8b-unit5-terrible", word: "terrible", meaning: "非常讨厌的；可怕的" },
        { id: "class8b-unit5-force", word: "force", meaning: "力；力量；强迫；迫使" },
        { id: "class8b-unit5-injury", word: "injury", meaning: "伤害；损伤" },
        { id: "class8b-unit5-death", word: "death", meaning: "死；死亡" },
        { id: "class8b-unit5-destroy", word: "destroy", meaning: "摧毁；破坏" },
        { id: "class8b-unit5-injure", word: "injure", meaning: "伤害；使受伤" },
        { id: "class8b-unit5-effect", word: "effect", meaning: "影响；作用" },
        { id: "class8b-unit5-rd", word: "Rd", meaning: "路；道路" },
        { id: "class8b-unit5-exam", word: "exam", meaning: "考试" },
        { id: "class8b-unit5-typhoon", word: "typhoon", meaning: "台风" },
        { id: "class8b-unit5-battery", word: "battery", meaning: "电池" },
        { id: "class8b-unit5-case", word: "case", meaning: "具体情况；事例；实例" },
        { id: "class8b-unit5-in-case", word: "in case", meaning: "以防；以防万一" },
        { id: "class8b-unit5-go-off", word: "go off", meaning: "断电" },
        { id: "class8b-unit5-pick-up", word: "pick up", meaning: "增强；改善；收拾" },
        { id: "class8b-unit5-lock", word: "lock", meaning: "锁住；把……锁起来" },
        { id: "class8b-unit5-anyway", word: "anyway", meaning: "不过；总之；而且；加之" },
        { id: "class8b-unit5-anybody", word: "anybody", meaning: "任何人；随便哪一个人" },
        { id: "class8b-unit5-low-flying", word: "low-flying", meaning: "低飞的" },
        { id: "class8b-unit5-cancel", word: "cancel", meaning: "取消；终止" },
        { id: "class8b-unit5-necessary", word: "necessary", meaning: "必要的；必需的" },
        { id: "class8b-unit5-electronic", word: "electronic", meaning: "电子的" },
        { id: "class8b-unit5-sharp", word: "sharp", meaning: "锋利的；锐利的；尖的" },
        { id: "class8b-unit5-bleed", word: "bleed", meaning: "流血；失血" },
        { id: "class8b-unit5-survive", word: "survive", meaning: "幸存" },
        { id: "class8b-unit5-similar", word: "similar", meaning: "相像的；相仿的；类似的" },
        { id: "class8b-unit5-rapid", word: "rapid", meaning: "迅速的；快速的；快捷的" },
        { id: "class8b-unit5-rapidly", word: "rapidly", meaning: "迅速地；快速地；快捷地" },
        { id: "class8b-unit5-towards", word: "towards", meaning: "向；朝着；接近" },
        { id: "class8b-unit5-hotel", word: "hotel", meaning: "旅馆；旅社" },
        { id: "class8b-unit5-nothing", word: "nothing", meaning: "没有什么；无关紧要的事" },
        { id: "class8b-unit5-whether", word: "whether", meaning: "是否" },
        { id: "class8b-unit5-get-away", word: "get away", meaning: "离开；逃离" },
        { id: "class8b-unit5-guard", word: "guard", meaning: "警卫；看守" },
        { id: "class8b-unit5-urge", word: "urge", meaning: "敦促；力劝" },
        { id: "class8b-unit5-super", word: "super", meaning: "超级的" },
        { id: "class8b-unit5-seaside", word: "seaside", meaning: "海边；海滨" },
        { id: "class8b-unit5-thunder", word: "thunder", meaning: "雷；雷声" },
        { id: "class8b-unit5-coast", word: "coast", meaning: "海岸；海滨" },
        { id: "class8b-unit5-rise", word: "rise", meaning: "上涨；升高" },
        { id: "class8b-unit5-injured", word: "injured", meaning: "受伤的" },
        { id: "class8b-unit5-rescue", word: "rescue", meaning: "营救；援救" },
        { id: "class8b-unit5-tent", word: "tent", meaning: "帐篷" }
      ]},
      { unitName: "Unit 6", words: [
        { id: "class8b-unit6-novel", word: "novel", meaning: "小说" },
        { id: "class8b-unit6-magical", word: "magical", meaning: "魔法的；神奇的" },
        { id: "class8b-unit6-cheerful", word: "cheerful", meaning: "开朗的；乐观的" },
        { id: "class8b-unit6-bad-tempered", word: "bad-tempered", meaning: "易怒的；爱发脾气的" },
        { id: "class8b-unit6-caring", word: "caring", meaning: "关心他人的；体贴的" },
        { id: "class8b-unit6-doubtful", word: "doubtful", meaning: "怀疑的；不确定的" },
        { id: "class8b-unit6-firm", word: "firm", meaning: "坚定的；坚决的" },
        { id: "class8b-unit6-tool", word: "tool", meaning: "工具" },
        { id: "class8b-unit6-seed", word: "seed", meaning: "种子；籽" },
        { id: "class8b-unit6-knife", word: "knife", meaning: "刀" },
        { id: "class8b-unit6-fork", word: "fork", meaning: "叉；餐叉" },
        { id: "class8b-unit6-packet", word: "packet", meaning: "密封小袋" },
        { id: "class8b-unit6-dead", word: "dead", meaning: "死的；枯萎的" },
        { id: "class8b-unit6-cheerleader", word: "cheerleader", meaning: "拉拉队队员；支持者" },
        { id: "class8b-unit6-yourself", word: "yourself", meaning: "你自己" },
        { id: "class8b-unit6-hers", word: "hers", meaning: "她的；属于她的" },
        { id: "class8b-unit6-whenever", word: "whenever", meaning: "无论何时；每当" },
        { id: "class8b-unit6-be-mean-to-sb", word: "be mean to sb", meaning: "对某人刻薄" },
        { id: "class8b-unit6-hardly", word: "hardly", meaning: "几乎不；几乎没有" },
        { id: "class8b-unit6-stare", word: "stare", meaning: "盯着看；凝视；注视" },
        { id: "class8b-unit6-stare-at", word: "stare at", meaning: "盯着看" },
        { id: "class8b-unit6-hang", word: "hang", meaning: "悬挂；吊" },
        { id: "class8b-unit6-hang-out", word: "hang out", meaning: "常去某处" },
        { id: "class8b-unit6-dig", word: "dig", meaning: "挖（土）；掘（地）" },
        { id: "class8b-unit6-neither", word: "neither", meaning: "两者都不" },
        { id: "class8b-unit6-as-if", word: "as if", meaning: "好像；仿佛" },
        { id: "class8b-unit6-lie", word: "lie", meaning: "躺；平躺" },
        { id: "class8b-unit6-ache", word: "ache", meaning: "疼痛；身体某部位的疼痛" },
        { id: "class8b-unit6-joke", word: "joke", meaning: "玩笑；笑话" },
        { id: "class8b-unit6-terribly", word: "terribly", meaning: "非常糟地；严重地" },
        { id: "class8b-unit6-finish", word: "finish", meaning: "完成；做好；结束" },
        { id: "class8b-unit6-over-the-moon", word: "over the moon", meaning: "欣喜若狂" },
        { id: "class8b-unit6-especially", word: "especially", meaning: "尤其；特别；非常" }
      ]}
    ]
  }
];
